### ISSUE TITLE
구조체 내용과 함수 정의

### ISSUE THREAD

**Issue by LedF1oyd** [2022OSSLJ/TeamProjectLJ#2]

**Comment by LSH-A** [comment]
구조체 내용 어떻게할까요?

**Comment by LedF1oyd** [comment]
중고차니깐 키로수, 연식, 제조사명, 모델 이름, 옵션 등이 있으면 될 것 같습니다.
그리고 간단한 설명이 들어갈 변수?

**Comment by LedF1oyd** [comment]
제조사 이름, 모델 이름, 글로 설명된 간단한 정보, 지역, 가격, 키로수, 연식, 주요 옵션

**Comment by LSH-A** [comment]
그러면 함수는 CRUD 네 개에 저장/읽어오기 2개 해서 6개, 그리고 검색으로 네 가지 이상 구현하면 될것 같은데
어떤 검색으로 할까요?

**Comment by LSH-A** [comment]
차종, 모델, 지역, 가격, 키로수 이렇게 다섯가지로 할까요?

**Comment by LedF1oyd** [comment]
키로수를 범위 지정해서 검색할 수 있으면 좋을 것 같네요! 좋습니다

**Comment by LSH-A** [comment]
정보 검색만 하는 것도 크게 의미 없으니 사용자간 거래 할수 있도록 구조체에 소유주 전화번호를 추가하는 것은 어떨까요?

**Comment by LedF1oyd** [comment]
아 그렇네요 좋습니다.
