### ISSUE TITLE
README 내용

### ISSUE THREAD

**Issue by LedF1oyd** [2022OSSLJ/TeamProjectLJ#3]
README 내용에 어떤 것을 넣을까요?

**Comment by LedF1oyd** [comment]
주제는 어떻게 쓸까요?

**Comment by LedF1oyd** [comment]
중고차 거래 사이트

**Comment by LedF1oyd** [comment]
소개: 중고차 매물 확인과 업로드가 가능하고 중고차 소유주와의 연락이 가능합니다?

**Comment by LedF1oyd** [comment]
기능 설명: 중고차에  대한 CRUD 기본 기능과 파일 저장 및 업로드, [차종, 모델, 지역, 가격, 키로수]를 통한 검색

**Comment by LSH-A** [comment]
소개는 중고차 정보로 사용자들을 연결 시켜주는 중고차 거래 프로그램 정도로 하면 될 것 같습니다!

**Comment by LedF1oyd** [comment]
아주 좋은 것 같습니다!

**Comment by LSH-A** [comment]
이미지는 이거 어떨까요?
https://pixabay.com/ko/photos/%ec%a4%91%ea%b3%a0-%ec%b0%a8%eb%9f%89-%ec%a7%80%ec%97%a0%ec%94%a8-%ed%8a%b8%eb%9f%ad-6893760/

**Comment by LedF1oyd** [comment]
https://www.istockphoto.com/kr/%EC%82%AC%EC%A7%84/%EC%B0%A8%EB%9F%89-%ED%8C%90%EB%A7%A4-gm672486518-123155087?utm_source=pixabay&utm_medium=affiliate&utm_campaign=SRP_image_sponsored&utm_content=http%3A%2F%2Fpixabay.com%2Fko%2Fimages%2Fsearch%2F%EC%A4%91%EA%B3%A0%EC%B0%A8%2F&utm_term=%EC%A4%91%EA%B3%A0%EC%B0%A8

**Comment by LedF1oyd** [comment]
언어는 C언어가 편할 것 같습니다.

**Comment by LSH-A** [comment]
그럼 개발환경 및 언어는 :gcc , C언어로 하면 되겠네요

**Comment by LedF1oyd** [comment]
> 그럼 개발환경 및 언어는 :gcc , C언어로 하면 되겠네요

넵!

**Comment by LSH-A** [comment]
역할분배는 어떻게 할까요?

**Comment by LedF1oyd** [comment]
제가 검색쪽 하면 될 것 같습니다

**Comment by LSH-A** [comment]
네 그럼 CRUD랑 파일 관련은 제가 할게요
