### ISSUE TITLE
CRUD 역할 분배 

### ISSUE THREAD

**Issue by LSH-A** [2022OSSLJ/TeamProjectLJ#6]
CRUD 역할 분배 어떻게 할까요?
기능 확인하려면 간단하게 함수 확인하는 main도 만들어야 할거같아요

**Comment by LedF1oyd** [comment]
맞네욥, 제가 main, C, U 하겠습니다.

**Comment by LedF1oyd** [comment]
제가 작성하고 PR 보내겠습니다~

**Comment by LSH-A** [comment]
그럼 제가 R,D랑 위키 수정까지 할게요!

**Comment by LedF1oyd** [comment]
넵 감사합니다~~!

**Comment by LedF1oyd** [comment]
main에서 menu를 list 해주는 함수도 필요할 것 같아서 만들겠습니다!
