### ISSUE TITLE
함수들 역할 분배

### ISSUE THREAD

**Issue by LSH-A** [2022OSSLJ/TeamProjectLJ#8]
나머지 함수들 구현하는건 어떻게 나눌까요?
저장 로드랑 검색 함수 몇가지 정도 남아있는것 같아요

**Comment by LedF1oyd** [comment]
제가 파일 저장, 불러오기 하면 될까요?

**Comment by LedF1oyd** [comment]
연락처 추가하고 알려주시면 제가 파일 저장 불러오기 완성시키겠습니다!

**Comment by LSH-A** [comment]
네 그럼 제가 검색 함수들 구현할게요!
